---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/abhi1-rithu2/nginxTask

